### ISSUE TITLE
Blender EEVEE

### ISSUE THREAD

**Issue by Gilfordo** [neverhood311/Stop-motion-OBJ#11]
Hello sir.

I thought you might be interested.

Situation: Right click, add sequence and instead of anything in viewport I have that message.

Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\mesh_sequence_controller.py", line 448, in execute
    obj = MSC.newMeshSequence()
  File "C:\Users\Josh\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\mesh_sequence_controller.py", line 127, in newMeshSequence
    scn.objects.link(theObj)
AttributeError: 'bpy_prop_collection' object has no attribute 'link'

location: <unknown location>:-1

**Comment by neverhood311** [comment]
Thanks for this! Working on a fix.

**Comment by neverhood311** [comment]
Either there's a bug in the most recent build of 2.80 or the Blender Python API seems to be different from that of 2.79 and earlier. The documentation on the 2.80 API is not complete yet. I'm gonna hold off on fixing this until we're closer to an official 2.80 release candidate, or whenever the API documentation is updated.

So that I don't forget, here are a few links that might be helpful when that time comes:
Blender documentation for updating scripts from 2.7x to 2.80: [Updating Scripts from 2.7x](https://wiki.blender.org/index.php/Dev:2.8/Source/Python/UpdatingScripts)

How to create objects in 2.7x: [Three ways to create objects](https://wiki.blender.org/index.php/Dev:Py/Scripts/Cookbook/Code_snippets/Three_ways_to_create_objects)

How to select objects in 2.7x: [Select an object via scripting](https://blender.stackexchange.com/questions/38618/selecting-an-object-via-scripting)

**Comment by Gilfordo** [comment]
That's interesting, thx for  help. Just thinking how to get water sim working live in the viewport while eevee in use. This is ex.  watch?v=iyaTCcfP2E8. All attributes missing when switched to eevee and ready done sim in cycles for ex. becomes a startup domain again in eevee.

**Comment by neverhood311** [comment]
A quick update. I found a helpful article, [https://wiki.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes](https://wiki.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes), which outlines a few changes to the Blender 2.80 Python API. I made some progress, but ran into another stumbling block, which is that the Blender OBJ import script is still broken in 2.80 ([https://developer.blender.org/T51937](https://developer.blender.org/T51937)). So until that's fixed, we're stuck again.

**Comment by neverhood311** [comment]
Closing since this seems to be a Blender issue, not an issue with this addon.

**Comment by neverhood311** [comment]
Just checked the latest build of Blender 2.80. Still no OBJ import. I'll keep checking every once in a while.
