### ISSUE TITLE
Render the OBJ sequence with motion blur?

### ISSUE THREAD

**Issue by Phonicavi** [neverhood311/Stop-motion-OBJ#114]
Sorry for bothering, I'm on the example:horse_gallop and I have tested on Blender-2.83.2, 2.90.1, and 2.91.0. However, the engine Cycles could not render the horse with motion blur correctly (it seems that Eevee does not support object blur or deformation blur before 2.90.x). Since I could guarantee the same number of vertices with the same order among all *.obj files, I was wondering is it possible to render the sequence with motion blur? Thanks in advance for any information about it :)

**Comment by neverhood311** [comment]
Unfortunately, motion blur is not possible with Stop Motion OBJ.

Motion blur in CG is achieved in one of two ways:

1. By rendering "in between" frames. When a ray is traced, it is given a fractional frame number that might fall in between two frame numbers. If there is continuous movement from one frame to the next, motion blur will appear as long as enough rays are traced at different fractional frame numbers. This method is physically accurate and is what Cycles does.

By design, Stop Motion OBJ doesn't allow for continuous movement from one frame to the next. It's just a sequence of static meshes with no information about movement. If you were to pick a fractional frame number in between two integer frame numbers and render it, you would see either the one frame or the other; there's no blending of meshes.

2. Using motion vectors and applying motion blur in the Compositor. Some applications will create a texture map for a moving object where the color at each point represents its motion vector for that frame. Each frame is rendered in two passes without motion blur: once with the correct colors and lighting, and once with only the motion vectors. To create motion blur, the two passes are combined in the Compositor using the [Vector Blur](https://docs.blender.org/manual/en/latest/compositing/types/filter/vector_blur.html) node. This method is fast, but less accurate, and doesn't work with reflections/refractions. Also, you need to have access to the motion vector maps (which the Horse Gallop sequence lacks).

As far as I know, the Blender OBJ, STL, and PLY importers don't support a motion vector texture map, so there's no way to render the motion vector pass. (The Alembic file format supports motion vectors AND mesh sequences. If you can export to Alembic, you might find some helpful information [here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Motion-Blur-Support))

I have some ideas for some time-consuming workarounds, but I won't describe them unless you're really really interested.

**Comment by Phonicavi** [comment]
Thanks for your patience! I guess maybe I need to concatenate all OBJs into an FBX scene by inserting many keyframes. :)
