### ISSUE TITLE
Perhaps use same name as the addon for easy identification

### ISSUE THREAD

**Issue by schroef** [neverhood311/Stop-motion-OBJ#120]
**Describe the solution you'd like**
The name mesh sequence is different then addon title, is confusing when one needs to find it.

**Describe alternatives you've considered**
Rename it same as addon name

**Comment by neverhood311** [comment]
Good suggestion. I almost did this in the last version, but I can't remember why I decided against it. I guess I'll do it in the upcoming version.

**Comment by schroef** [comment]
I hope you dont mind me suggestion it. I was a bit confused about the different naming of it. Because its called Stop-motion-obj but then in blender its called mesh sequence. It does do different filetypes right? Then mesh sequence is a more pr opiate name. Perhaps make it "Mesh Sequence Importer" that immediately indicates its purpose.

**Comment by neverhood311** [comment]
I don't mind the suggestion at all!

> It does do different filetypes right?

Yeah, it supports .obj, .stl, and .ply.

> i thought it could do FBX and others as well. just looked at it again. Havent you thought of adding more file formats?

The three supported formats (again, .obj, .stl, and .ply), were chosen because they contain only geometric data, and not much else. I didn't think it made sense to import a sequence of other formats (FBX, Collada, and glTF, for example) because those formats can include additional data such as cameras, lighting, scene hierarchies, and animation. If each file in the sequence contained its own animation, it's not clear what I should do with those animations. Also, I wanted to avoid the complexity of importing files that contain multiple objects.

I chose not to support Alembic sequences since Blender already supports that by default. 

If you can think of a good use-case for any of the other import formats (BVH, SVG, X3D), or want to try to change my mind about FBX, I'm happy to hear you out.

**Comment by neverhood311** [comment]
FYI, I changed the section's name in this PR: https://github.com/neverhood311/Stop-motion-OBJ/pull/150
It'll show up when the next version is released, hopefully before the end of the year.
