### ISSUE TITLE
Materials per frame are not loading in sequence

### ISSUE THREAD

**Issue by jillianhmorrow** [neverhood311/Stop-motion-OBJ#13]
I'm trying to import an obj sequence that has a unique .mtl and texture file per frame. I know this feature was added with the latest update, but when I import the sequence (with material per frame selected) only the first texture shows up. The rest of the frames are white. Any recommendations?

**Comment by neverhood311** [comment]
Can you share a few frames (at least 3 or so) of your sequence with me so I can do some debugging?

**Comment by neverhood311** [comment]
Important follow-up questions: Are you using a release from the Master branch? Also, what version of Blender are you using? The script still doesn't work in Blender 2.8 beta.

**Comment by jillianhmorrow** [comment]
Hi Justin,

Thanks so much for your quick response! I've uploaded the test sequence here
<https://www.dropbox.com/s/wwixmc5np2mketp/OBJ_JM.zip?dl=0>. I used the
release from the Master branch. Is there another that I should be using?
Also, I am using Blender v.2.79.

Jillian

**Comment by neverhood311** [comment]
Hi Jillian,

Apparently I was able to download from your Dropbox link before you edited your comment. Is that sequence still valid? If so, have you tried importing just one of your OBJs using the regular method (File > Import > Wavefront (.obj))? I tried that and the textures still didn't appear, even when switching to Textured, Material, and Rendered views.

FYI, for Blender 2.79, you should use release 1.1.0, as you have done. There's an open branch for the Blender 2.80-compatible version of the script. Just wanted to make sure you weren't using that since it's not finished.

**Comment by neverhood311** [comment]
Closing since it seems like an issue either with the specific OBJ and MTL files or Blender itself
