### ISSUE TITLE
Importing OBJ sequence that have different framerate than Scene timeline.

### ISSUE THREAD

**Issue by softyoda** [neverhood311/Stop-motion-OBJ#43]
As written in the title, I'm facing a problem, I got some point cloud data from kinect (ply) and I wanted to visualize it in my 3D animation.

The only problem is that the data I have is from an older generation kinect that seems to film in 15fps.

However I need to do some traveling at least in 25 or 30fps.

Is there a way i can import a 15fps ply sequence to a 30fps scene, or scale keyframes in dopesheet ?

**Comment by neverhood311** [comment]
> Is there a way i can import a 15fps ply sequence to a 30fps scene?

Yes. Import your sequence like normal, then change the Playback Speed. In your case, you'd want the playback speed to be 0.5. The playback speed for your mesh sequence is: `mesh sequence fps / scene fps`. Stop motion OBJ will simply show each of your .ply meshes for two frames.

15 and 30 work really well together since 30 is a multiple of 15. If you were to do 15 and 25, things wouldn't work out quite so nicely. Some of your frames would appear for two frames while others would appear for only one frame, which would make for a weirdly-jittery appearance.

**Comment by neverhood311** [comment]
@softyoda Have you had a chance to try out my suggestion?

**Comment by softyoda** [comment]
Hello, no sorry, I couldn't perform the manipulation you say. 
If I create a .blend file that I set to 15fps and import the sequence, it's the right time size, but the camera paths is not convenient if playback at 15fps.

If I change the number of FPS from 15 to 30, the PLY sequence doesn't match the right timming anymore.
I tried with time remapping, but I don't master/understand its behavior well.


The PLY sequence corresponds to a point cloud of a musician, so it must be in sync with a music and therefore have a good syncronization even though it was recorded at 15fps.

Thank you for your help

**Comment by neverhood311** [comment]
There's no need to use Blender Time Remapping.
Maybe my suggestion could have been more clear. Try this:

* Create your .blend file and set it to 30 fps:
![set_to_30fps_50](https://user-images.githubusercontent.com/4615170/81089195-48d16d80-8eb9-11ea-8f02-3fa8d06d224a.png)


* Import your mesh sequence
* Change your mesh sequence Playback Speed to 0.5:
![SMO_playback_speed_50](https://user-images.githubusercontent.com/4615170/81089094-28091800-8eb9-11ea-898e-50702e988c4a.png)

When you play the animation, the timing should be correct. Let me know if this works for you.

**Comment by softyoda** [comment]
Thank you, that solved my problem.

Yes, I was looking too far away, but the solution remains simple, thank you very much.
