### ISSUE TITLE
Blender always pkill's itself.

### ISSUE THREAD

**Issue by NicTanghe** [neverhood311/Stop-motion-OBJ#52]
**System Information**
Operating system:

linux x64 arch instantos.
3950x amd
750ti Nvidea

**Addon version**
Broken: ( 2.0.2)
Worked: (no idea)

**Steps To Reproduce**
import large set of more 100+ frames.

**Expected behavior**
it doesn't pkill itself

**explanation**

Blender pkills itself either during the process of importing at a random 100+ frame or when it has done the last step.

**Console**
```

 
 (  0.0000 sec |   0.0000 sec) Importing OBJ '/home/tanghe/Houdini/mandelbulb/OBJ/1/mandelbulb99.obj'...
  (  0.0050 sec |   0.0048 sec) Parsing OBJ file...
    ( 12.6338 sec |  12.6284 sec) Done, loading materials and images...
    ( 12.6360 sec |  12.6306 sec) Done, building geometries (verts:2015632 faces:2014342 materials: 1 smoothgroups:0) ...
    ( 18.7850 sec |  18.7796 p
 
Info: Deleted 1 object(s)
[1]    47465 killed     blender

```

**Comment by neverhood311** [comment]
I've never before encountered this error (in Windows) while importing.

Roughly how large is each of your meshes? Would you be able to share a subset so I can test on my end?

**Comment by NicTanghe** [comment]
between 100 mb and 210 mb. so i have no idea where i could make these available to u

**Comment by neverhood311** [comment]
So you're importing 100+ files that are 100+ MB each? I'm willing to bet you're just running out of memory. Versions 2.0.2 and earlier attempt to load the entire sequence into memory. As a very conservative estimate, you're loading at least 10,000 MB into Blender.

I'm currently working on the next major version of the addon and I've included a feature to address this specific issue. Instead of loading the entire sequence at the beginning, it loads meshes on-demand, then deletes them once they're no longer needed. I'm currently looking for alpha/beta testers for the next version. Would you be willing to try it out?

**Comment by NicTanghe** [comment]
ive have spend around 2 days on trying to get this to work so yes i'm verry willing to try it out.

**Comment by neverhood311** [comment]
Ok, try installing this version of the addon: [3.0.0-alpha.9](https://github.com/neverhood311/Stop-motion-OBJ/tree/version-3). You'll have to uninstall or disable your existing version first. And you might have to manually copy the new version into your addons folder.

Also, the way you import a sequence has changed. Instead of doing Add > Mesh > Mesh Sequence, you have to do File > Import > Mesh Sequence. That will bring up the file import window. Just navigate to the folder where your sequence is located, fill in the file name prefix, and change `Cache Mode` from `Cached` (which imports every mesh at the beginning) to `Streaming` (which loads meshes on demand). Don't select any files, just leave the big text box blank. Once the first mesh loads, go look at the Mesh Sequence settings. Change your `Cache Size` to 2 or 3 or so (this is how many meshes Blender will keep in memory at any given time. '0' means "keep everything"). Whenever you go to the next frame, the addon will load the next mesh if it's not already in memory. If you don't want it to automatically load meshes, just uncheck the `Stream Meshes During Playback` box.

**Comment by NicTanghe** [comment]
anny where that addon folder is on linux ?

**Comment by neverhood311** [comment]
I don't know off the top of my head, but see [this post](https://blender.stackexchange.com/questions/30467/where-are-the-blender-program-files-in-ubuntu-14-04). Hopefully this answer applies to your OS also.

**Comment by NicTanghe** [comment]
Do i just git clone it or ?

**Comment by neverhood311** [comment]
You can clone it or just download the source as a ZIP.

**Comment by NicTanghe** [comment]
this fixes the issue thx dude.

**Comment by neverhood311** [comment]
Good to hear. I'm hoping to start Beta testing within a few weeks, then release a final version sometime during Summer 2020.

**Comment by sikkeep** [comment]
@neverhood311 Can you help me? i'm just import -> Mesh sequence. after i'm try to import all 246 files with format .obj, but hapen blender glitch. blender try to upload this files and throw me error "blender not responding".
Blender v2.82.7
Stop-motion-OBJ v2.1.0 and try v2.1.1 same errors
